version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi4-homeassistant:0.107.7
    volumes:
      - ./config/home-assistant/:/config
    environment:
      - TZ=Europe/Paris
    restart: always
    network_mode: host

