version: '3'
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/raspberrypi3-homeassistant:stable
    volumes:
      - ./config/home-assistant/:/config
    environment:
      - TZ=Europe/Paris
    restart: always
    network_mode: host

  rhasspy:
    container_name: rhasspy
    image: "synesthesiam/rhasspy-server:latest"
    restart: always
    network_mode: host
    volumes:
      - "./config/rhasspy/profiles:/profiles"
    devices:
      - "/dev/snd:/dev/snd"
    command: --user-profiles /profiles --profile fr

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - ./config/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Paris
