
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

homeassistant:
  time_zone: Europe/Paris

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
# tts:
#   - platform: google_translate
rest_command:
  tts:
    url: http://localhost:12101/api/text-to-speech
    method: POST
    payload: '{{ message }}'
  volume:
    url: 'http://localhost:15000/api/volume'
    method: POST
    headers:
      content-type: 'application/x-www-form-urlencoded'
    payload: 'value={{ value }}{% if action is defined %}&action={{ action }}{% endif %}'
  beep:
    url: 'http://localhost:15000/api/play-beep'

group: !include groups.yaml
automation: !include_dir_merge_list automation/
script: !include scripts.yaml
scene: !include scenes.yaml
