sensor.disk_use_percent:
  icon: mdi:micro-sd
sensor.swap_use_percent:
  icon: mdi:micro-sd

person.bryton_lacquement:
  friendly_name: Bryton
  entity_picture: https://cdn.bminusl.xyz/images/bminusl.png
