views:
  - path: maison
    title: Maison
    cards:
      - type: light
        entity: light.bedroom_1_light_1_light
        name: Chambre
      - type: weather-forecast
        entity: weather.maison
      - type: map
        aspect_ratio: 16:9
        default_zoom: 8
        entities:
          - zone.home
      - type: iframe
        # XXX: We need to access ":15000", but I don't want to hardcode the
        # host, e.g. "foobarbaz:15000". The following solution is a workaround;
        # see <config-directory>/www/port-15000.html
        url: /local/port-15000.html
  - path: zigbee2mqtt
    title: Zigbee2mqtt
    badges:
      - entity: sensor.coordinator_version
      - entity: sensor.zigbee2mqtt_version
      - entity: sensor.zigbee2mqtt_bridge_state
    cards:
      - type: entities
        title: Autoriser les appareils à rejoindre
        entities:
          - switch.zigbee2mqtt_main_join
          - timer.zigbee_permit_join
  - path: system
    title: Système
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Ressources
          - type: sensor
            entity: sensor.cpu_temperature
            graph: line
            name: CPU
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.processor_use
                graph: line
                name: CPU
              - type: sensor
                entity: sensor.memory_use_percent
                graph: line
                name: RAM
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.disk_use_percent
                graph: line
                name: Micro SD
              - type: sensor
                entity: sensor.swap_use_percent
                graph: line
                name: Swap

      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Réseau
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.ipv4_address_eth0
                name: Adresse IPv4
