views:
  - path: zigbee2mqtt
    title: Zigbee2mqtt
    badges:
      - entity: sensor.coordinator_version
      - entity: sensor.zigbee2mqtt_version
      - entity: sensor.zigbee2mqtt_bridge_state
    cards:
      - type: entities
        title: Autoriser les appareils à rejoindre
        entities:
          - switch.zigbee2mqtt_main_join
          - timer.zigbee_permit_join
