views:
  - path: maison
    title: Maison
    cards:
      - type: light
        entity: light.bedroom_1_light_1_light
        name: Chambre
      - type: weather-forecast
        entity: weather.maison
      - type: map
        aspect_ratio: 16:9
        default_zoom: 8
        entities:
          - zone.home
      - type: iframe
        url: http://raspberrypi.local:15000
  - path: zigbee2mqtt
    title: Zigbee2mqtt
    badges:
      - entity: sensor.coordinator_version
      - entity: sensor.zigbee2mqtt_version
      - entity: sensor.zigbee2mqtt_bridge_state
    cards:
      - type: entities
        title: Autoriser les appareils à rejoindre
        entities:
          - switch.zigbee2mqtt_main_join
          - timer.zigbee_permit_join
