resources:
  - url: /local/mini-graph-card-bundle.js?v=0.9.3
    type: module
views:
  - path: maison
    title: Maison
    icon: mdi:home
    cards:
      - type: light
        entity: light.bedroom_1_light_1_light
        name: Chambre
      - type: weather-forecast
        entity: weather.maison
      - type: map
        aspect_ratio: 16:9
        default_zoom: 8
        entities:
          - zone.home
      - type: iframe
        # XXX: We need to access ":15000", but I don't want to hardcode the
        # host, e.g. "foobarbaz:15000". The following solution is a workaround;
        # see <config-directory>/www/port-15000.html
        url: /local/port-15000.html
  - path: zigbee2mqtt
    title: Zigbee2mqtt
    icon: mdi:zigbee
    badges:
      - entity: sensor.coordinator_version
      - entity: sensor.zigbee2mqtt_version
      - entity: sensor.zigbee2mqtt_bridge_state
    cards:
      - type: entities
        title: Autoriser les appareils à rejoindre
        entities:
          - switch.zigbee2mqtt_main_join
          - timer.zigbee_permit_join
  - path: system
    title: Système
    icon: mdi:raspberry-pi
    cards:
      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Ressources
          - type: custom:mini-graph-card
            entities:
              - entity: sensor.cpu_temperature
                name: CPU
            hour24: true
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - entity: sensor.processor_use
                    name: CPU
                hour24: true
                line_width: 10
              - type: custom:mini-graph-card
                entities:
                  - entity: sensor.memory_use_percent
                    name: RAM
                hour24: true
                line_width: 10
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - entity: sensor.disk_use_percent
                    name: Micro SD
                hour24: true
                line_width: 10
              - type: custom:mini-graph-card
                entities:
                  - entity: sensor.swap_use_percent
                    name: Swap
                hour24: true
                line_width: 10

      - type: vertical-stack
        cards:
          - type: markdown
            content: >
              ## Réseau
          - type: horizontal-stack
            cards:
              - type: sensor
                entity: sensor.ipv4_address_eth0
                name: Adresse IPv4
