resources:
  - url: /local/mini-graph-card-bundle.js?v=0.9.3
    type: module
  - url: /local/custom-header.js?v=1.3.2
    type: module
custom_header:
  compact_mode: true
  options_hide: true

  # Google Light Theme
  background: var(--app-header-background-color)
  elements_color: var(--app-header-text-color)
  active_tab_color: var(--state-icon-active-color)
  tab_indicator_color: var(--state-icon-active-color)
views:
  - !include views/home.yaml
  - !include views/zigbee2mqtt.yaml
  - !include views/system.yaml
