- alias: "Tell the time"
  trigger:
    platform: event
    event_type: rhasspy_GetTime
  action:
    - service: rest_command.tts
      data_template:
        message: >
          Il est {{ now().strftime("%H:%M") }}.

- alias: 'Set theme at startup'
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: Google Light Theme
