path: system
title: Système
icon: mdi:raspberry-pi
cards:
  - type: vertical-stack
    cards:
      - type: custom:mini-graph-card
        entities:
          - entity: sensor.cpu_temperature
            name: CPU
        hour24: true
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - entity: sensor.processor_use
                name: CPU
            hour24: true
            line_width: 10
          - type: custom:mini-graph-card
            entities:
              - entity: sensor.memory_use_percent
                name: RAM
            hour24: true
            line_width: 10
      - type: horizontal-stack
        cards:
          - type: custom:mini-graph-card
            entities:
              - entity: sensor.disk_use_percent
                name: Disque
            hour24: true
            line_width: 10
          - type: custom:mini-graph-card
            entities:
              - entity: sensor.swap_use_percent
                name: Swap
            hour24: true
            line_width: 10

  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            entity: sensor.ipv4_address_eth0
            name: Adresse IPv4
          - type: custom:mini-graph-card
            name: Trafic
            icon: mdi:gauge
            entities:
              - entity: sensor.network_throughput_in_eth0
                name: Réception
              - entity: sensor.network_throughput_out_eth0
                name: Envoi
            hour24: true
            line_width: 10
            points_per_hour: 120 # Every 30 seconds
            hours_to_show: 0.1666667 # 10 minutes
