path: zigbee2mqtt
title: Zigbee2mqtt
icon: mdi:zigbee
cards:
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            entity: sensor.zigbee2mqtt_version
            name: Version
          - type: sensor
            entity: sensor.zigbee2mqtt_bridge_state
            name: État du pont
      - type: sensor
        entity: sensor.coordinator_version
        name: Coordinateur
  - type: vertical-stack
    cards:
      - type: entities
        title: Ajouter des appareils
        entities:
          - entity: switch.zigbee2mqtt_main_join
            name: Autoriser à rejoindre
          - entity: timer.zigbee_permit_join
            name: Temps restant
