- alias: "Control the bedroom light"
  trigger:
    platform: mqtt
    topic: zigbee2mqtt/bedroom_1_switch_1
  condition:
    condition: template
    value_template: "{{ trigger.payload_json.action not in (undefined, '') }}"
  action:
    - service: python_script.handle_hue_dimmer_switch
      data_template:
        action: '{{ trigger.payload_json.action }}'
        brightness: '{{ trigger.payload_json.brightness }}'
        target_id: light.bedroom_1_light_1_light
